import 'package:isar/isar.dart';

part 'patient_local.g.dart'; // generated by: dart run build_runner build

/// Triage status shown as a color-coded dot on the ASHA [PatientListScreen].
/// green = ok, amber = warning, red = missed routine / cognitive-decline alert.
enum PatientStatus { ok, warning, alert }

/// A patient record cached on the ASHA device so the list works fully offline.
/// Refreshed from the backend when connectivity allows.
@collection
class PatientLocal {
  Id id = Isar.autoIncrement;

  @Index(unique: true, replace: true)
  late String patientId;

  late String displayName;

  /// Path to a locally cached photo (patients are recognised by face, not name).
  String? photoPath;

  @enumerated
  PatientStatus status = PatientStatus.ok;

  /// Fraction of today's routine completed, 0..1.
  double routineCompliance = 0;

  DateTime? lastRoutineAt;
  bool missedRoutineToday = false;
  bool cognitiveDeclineAlert = false;

  /// When this cache row was last reconciled with the server.
  DateTime updatedAt = DateTime.fromMillisecondsSinceEpoch(0);
}
