import 'package:isar/isar.dart';

part 'sync_envelope.g.dart'; // generated by: dart run build_runner build

enum SyncKind { telemetry, routineCompletion }

/// A single durable row in the offline outbox. Every write the patient makes
/// becomes a [SyncEnvelope] with `synced=false`; [SyncManager] drains it to the
/// backend in idempotent batches and flips `synced=true` only on server ACK.
@collection
class SyncEnvelope {
  Id id = Isar.autoIncrement;

  /// Client-generated idempotency key — dedupes retried batches server-side.
  @Index(unique: true, replace: true)
  late String eventId;

  @enumerated
  late SyncKind kind;

  /// JSON-encoded payload (e.g. a serialized TelemetryEvent).
  late String payloadJson;

  late DateTime createdAt;

  @Index()
  bool synced = false;

  int attempts = 0;
  String? lastError;

  /// Backoff gate — [SyncManager] skips rows whose retry time is in the future.
  DateTime? nextAttemptAt;
}
